feature/157 First speaker hero version
Schrodinger-Hat/osday-2023 pull request #165
Opened 2023-01-25 15:38 UTC by 404answernotfound

Solves #157

2023-01-25 17:18 UTC, Wabri commented
Like it 🤟

2023-01-25 17:21 UTC, nicpuppa commented
Nice job

2023-01-25 17:42 UTC, 404answernotfound commented
Draft until completed

2023-01-25 17:46 UTC, TheJoin95 commented
Bella idea! Farei anche a mo' di timeline, ovvero al centro dello schermo una linea che scende giù in maniera verticale con dei keyframe indicanti l'orario di inizio talk. A destra e a sinistra, un po' come un albero binario, abbiamo gli speaker.

Questo era il feedback sulla pagina agenda.

Per la hero: immagine un po' più grande, hero cliccabile per un eventuale dettaglio dello speaker e talk (?), aumenterei un po' di più il contrasto tra lo sfondo e la card, magari anche con una ombra di un grigio leggero (?)

2023-02-07 12:32 UTC, TheJoin95 reviewed
Watch out for the responsiveness

2023-02-07 16:49 UTC, TheJoin95 approved these changes

2023-02-07 16:50 UTC, TheJoin95 reviewed
Possiamo formattare un po' meglio il testo? Con dei ritorni a capo magari, è l'unico appunto ecco

2023-02-07 16:59 UTC, nicpuppa commented
> Possiamo formattare un po' meglio il testo? Con dei ritorni a capo magari, è l'unico appunto ecco

Se viene semplice inserendo la formattazione nell’i18n si, sennò probabilmente è un dito nel …

2023-02-07 17:36 UTC, TheJoin95 commented
> > Possiamo formattare un po' meglio il testo? Con dei ritorni a capo magari, è l'unico appunto ecco
> 
> Se viene semplice inserendo la formattazione nell’i18n si, sennò probabilmente è un dito nel …

Dovrebbe esser semplice, mi sembra si era già fatto broski

2023-02-08 13:17 UTC, davideimola requested changes
Can we just create a standard for the subtitle under the Speaker? Something like

```Job Position at Company
GitHub Star・MVP・GDE```

2023-02-09 08:44 UTC, AngyDev approved these changes

2023-02-10 10:36 UTC, Wabri approved these changes

2023-02-10 10:51 UTC, merged