Add OVH as Diamond Sponsor #162
Schrodinger-Hat/osday-2023 pull request #166
Opened 2023-01-25 17:23 UTC by Nareshchoudhary02

Add OVH as Diamond Sponsor
#162 done. Just add ovhcloud_logo.svg and that's it.😄

2023-01-25 17:25 UTC, nicpuppa requested changes

2023-01-25 17:25 UTC, nicpuppa commented on package-lock.json
> +  "lockfileVersion": 3,
@Nareshchoudhary02 can you please revert these changes ?

2023-01-25 17:25 UTC, nicpuppa requested changes
@Nareshchoudhary02 can you please revert the changes on package-lock.json ?

2023-01-25 17:29 UTC, Nareshchoudhary02 commented
ok let me revert package-lock.json

2023-01-25 17:30 UTC, nicpuppa requested changes
@Nareshchoudhary02 also you forget to upload the logo into public folder

2023-01-25 17:47 UTC, Nareshchoudhary02 commented
Hello, I am new to the open source contribution community and I would greatly appreciate any guidance or advice on how to get started. Thank you

2023-01-25 18:06 UTC, nicpuppa commented
> Hello, I am new to the open source contribution community and I would greatly appreciate any guidance or advice on how to get started. Thank you

What you have done so far is great! Looking for some good first issue, ask to the maintainers of the project to take an issue, fork the repo and open your first PR, these are the step to follow to contribute to an open-source project!

We also have a discord server (https://discord.com/invite/RTXr8A3eFn), feel free to join and ask whatever you want.

To conclude this issue, you need to upload the image file in the correct folder!

2023-01-25 18:10 UTC, Nareshchoudhary02 commented
> 

I uploaded a logo to the public folder but facing an issue because I requested too many merge requests it is messed up.

2023-01-26 13:12 UTC, nicpuppa commented
@Nareshchoudhary02 can you please update the logo that you upload yesterday with this one ? 

![OVHcloud_stacked_logo_white_RGB](https://user-images.githubusercontent.com/72783243/214844030-f2adf238-f830-4411-a352-87f7740de036.svg)

2023-01-26 13:19 UTC, Nareshchoudhary02 commented
> @Nareshchoudhary02 can you please update the logo that you upload yesterday with this one ?
> 
> ![OVHcloud_stacked_logo_white_RGB](https://user-images.githubusercontent.com/72783243/214844030-f2adf238-f830-4411-a352-87f7740de036.svg)

ok on it.

2023-01-26 13:29 UTC, Nareshchoudhary02 commented
> @Nareshchoudhary02 can you please update the logo that you upload yesterday with this one ?
> 
> ![OVHcloud_stacked_logo_white_RGB](https://user-images.githubusercontent.com/72783243/214844030-f2adf238-f830-4411-a352-87f7740de036.svg)

It's done 😄. I have question how you converted got svg of image I want to know , because svg are more scalable.

2023-01-26 13:49 UTC, nicpuppa commented
> It's done smile. I have question how you converted got svg of image I want to know , because svg are more scalable.

The company provide us the correct image (svg in this case)

2023-01-26 13:49 UTC, merged