feat/added permission policy
Schrodinger-Hat/osday-2023 pull request #216
Opened 2023-03-08 14:08 UTC by 404answernotfound

2023-03-08 17:34 UTC, davideimola approved these changes

2023-03-08 18:47 UTC, nicpuppa requested changes
@404answernotfound can you please remove the Privacy Policy link in the footer ? Also remove the page as well

![IMG_2433](https://user-images.githubusercontent.com/72783243/223806764-da0294a6-73fb-466e-a280-10ac12cb12b6.jpeg)

2023-03-08 19:06 UTC, Wabri requested changes

2023-03-08 19:06 UTC, Wabri commented on pages/privacy-and-permissions.tsx
> +            Schrodinger Hat, in persona dei soci Michele Lombardi, Gabriele
```suggestion
            Schrodinger Hat, in persona dei soci Miki Lombardi, Gabriele
```

2023-03-09 11:02 UTC, nicpuppa approved these changes

2023-03-09 11:10 UTC, TheJoin95 commented on components/Footer.tsx
> +              <Link href={'/privacy-and-permissions'}>{t('privacy_permissions')}</Link>
Indent pls

2023-03-09 11:11 UTC, TheJoin95 commented on pages/privacy-and-permissions.tsx
> +          <h3>Oggetto del trattamento</h3>
We should specify either that the text is available only in italian, which is not good, or to add the text in the i18n. What do you think

2023-03-09 11:13 UTC, TheJoin95 commented on pages/privacy-and-permissions.tsx
> +          </p>
Eviterei di inserire questo dato che non è relativo all'evento e alla gestione dei dati in questione

2023-03-09 11:14 UTC, TheJoin95 commented on pages/privacy-and-permissions.tsx
> +                obbligo di conservazione delle scritture contabili);
??

2023-03-09 11:21 UTC, TheJoin95 approved these changes

2023-03-09 11:26 UTC, Wabri approved these changes

2023-03-09 11:27 UTC, merged