feat(494): add mc info in agenda
Schrodinger-Hat/osday-2023 pull request #495
Opened 2024-03-01 14:48 UTC by TheJoin95

Closes #494 

![image](https://github.com/Schrodinger-Hat/osday/assets/6616203/7d945d53-c2b3-419a-b8b3-b86e3791010e)

2024-03-01 14:51 UTC, davideimola approved these changes, later dismissed

2024-03-02 14:39 UTC, Wabri requested changes
Leave this open until I get the last 2 confirmation!

2024-03-02 15:31 UTC, Wabri commented
Would you mind to update the MCs with this?

Day 7 morning: Maciek Palmowski + Lorenzo Pieri
Day 7 afternoon: Irine Kokilashvili + Miki Lombardi
Day 8 morning: Noah Jelich + Miki Lombardi
Day 8 afternoon: Sabrina Mazzola + Lorenzo Pieri

2024-03-02 15:34 UTC, Wabri requested changes

2024-03-02 15:34 UTC, Wabri commented on pages/agenda.tsx
> +              <AgendaCard hour='9:50' isBreak={true} breakTitle='Morning intro' subtitle='Presented by Lorenzo Pieri' icon='/icons/microphone.svg' position='left'/>
```suggestion
              <AgendaCard hour='9:50' isBreak={true} breakTitle='Morning intro' subtitle='Presented by Lorenzo Pieri & Maciek Palmowski' icon='/icons/microphone.svg' position='left'/>
```

2024-03-02 15:34 UTC, Wabri commented on pages/agenda.tsx
> +              <AgendaCard hour='14:00' isBreak={true} breakTitle='Afternoon intro' subtitle='Presented by Miki Lombardi & Maciek Palmowski' icon='/icons/microphone.svg' position='right'/>
```suggestion
              <AgendaCard hour='14:00' isBreak={true} breakTitle='Afternoon intro' subtitle='Presented by Miki Lombardi & Irine Kokilashvili' icon='/icons/microphone.svg' position='right'/>
```

2024-03-02 15:34 UTC, Wabri commented on pages/agenda.tsx
> +              <AgendaCard hour='14:00' isBreak={true} breakTitle='Afternoon intro' subtitle='Presented by Lorenzo Pieri' icon='/icons/microphone.svg' position='right'/>
```suggestion
              <AgendaCard hour='14:00' isBreak={true} breakTitle='Afternoon intro' subtitle='Presented by Lorenzo Pieri &Sabrina Mazzola' icon='/icons/microphone.svg' position='right'/>
```

2024-03-02 17:07 UTC, Wabri approved these changes

2024-03-02 17:07 UTC, merged